global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'microservices'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: 
        - 'gateway-service:8080'
        - 'patient-service:8081'
        - 'medecin-service:8082'
        - 'prediction-service:8083'
        - 'gestion-service:8084'
        - 'security-service:8085'
        - 'supervision-service:8086'
        - 'eureka-server:8761'
        - 'config-service:8888'
